# Generated by Django 6.0.1 on 2026-01-28 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du lien')),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('icon', models.CharField(blank=True, help_text="Classe CSS de l'icône (ex: fab fa-twitter)", max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Lien',
                'verbose_name_plural': 'Liens',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'accès")),
                ('via_qrcode', models.BooleanField(default=False, verbose_name='Via QR Code')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name="Type d'appareil")),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app_linktree.link', verbose_name='Lien')),
            ],
            options={
                'verbose_name': 'Statistique de lien',
                'verbose_name_plural': 'Statistiques de liens',
                'ordering': ['-created_at'],
            },
        ),
    ]
